[project]
name = "piper-api"
version = "0.1.0"
description = "Piper HTTP API server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.117.1",
    "piper>=0.14.5",
    "piper-tts>=1.3.0",
    "uvicorn>=0.37.0",
]
